### ISSUE TITLE
Django 3 support

### ISSUE THREAD

**Issue by bastiaan85** [tokibito/django-ftpserver#20]
On Django 3.0 django-ftpserver will cause a fatal exception

    ImportError: cannot import name 'python_2_unicode_compatible'

caused by using the Python 2 compatible API that has been depracated since 2.0 but has been removed in 3.0. It might be useful to use the PR used to make django-simple-history 3.0 compatible available [here](https://github.com/treyhunner/django-simple-history/pull/610/commits/9577799aebd4ea99abee47e190c2456c964f2f08) as guidance for fixing the issue here too.

**Comment by tokibito** [comment]
Thanks. I will adjust code for that works with Django 3.0.

**Comment by tokibito** [comment]
I just released version 0.7.0. It supports Django 3.0.
